export const MESSAGES_FAILED_TO_LOAD = 'MESSAGES_FAILED_TO_LOAD';
export const MESSAGES_LOADING = 'MESSAGES_LOADING';
export const MESSAGES_LOADED = 'MESSAGES_LOADED';
export const MEMBERS_FAILED_TO_LOAD = 'MEMBERS_FAILED_TO_LOAD';
export const MEMBERS_LOADING = 'MEMBERS_LOADING';
export const MEMBERS_LOADED = 'MEMBERS_LOADED';
